name: Deploy Infrastructure 

on:
  push:
    branches: [main]
    paths:
      - 'restaurant-finder-infra/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11.5'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Install CDK dependencies
        working-directory: ./restaurant-finder-infra
        run: |
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: CDK Bootstrap 
        working-directory: ./restaurant-finder-infra
        run: |
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/ap-south-1 || true

      - name: CDK Deploy
        working-directory: ./restaurant-finder-infra
        run: cdk deploy --all --require-approval never
